version: "3.8"

services:
  backend:
    build: ./backend
    container_name: fastapi_app
    ports:
      - "8002:8002"

  frontend:
    build: ./frontend
    container_name: html_app
    ports:
      - "8080:80"
